### ISSUE TITLE
AssemblyName ignored when referencing .csproj project

### ISSUE THREAD

**Issue by mistiara** [georgewfraser/fsharp-language-server#23]
The language server seems to ignore the `AssemblyName` of referenced `.csproj` files, failing to reference the assembly when the name differs from the project filename. I found this out while trying to reference third-party projects that have multiple `.csproj` as they transition to netstandard and the new project format.

I'm using the latest version published for VS Code.

Minimal repro:

1. `dotnet new classlib -n Foo` (this is a C# project)
2. Add to `Foo.csproj` an `AssemblyName` property different than `Foo`, e.g. `Different`
3. `dotnet new classlib -n Bar -lang F#`
4. `dotnet add Bar reference Foo`
5. Open the namespace `Foo` in `Bar/Library.fs`
6. Build Bar

Both Foo and Bar will build successfully, but the language server will try to reference `Foo.dll` instead of `Different.dll` and fail.

**Comment by georgewfraser** [comment]
If you're interested in working on this, I believe the problem is in the projectTarget function:

https://github.com/georgewfraser/fsharp-language-server/blob/3399a0391d7036afbb8cb21753b469b16d001e1e/src/ProjectCracker/ProjectCracker.fs#L343

You should be able to make an automated test that reproduces this problem by making a sample project in samples/ and then following the pattern in ProjectCrackerTests.fs:

https://github.com/georgewfraser/fsharp-language-server/blob/3399a0391d7036afbb8cb21753b469b16d001e1e/tests/ProjectCracker.Tests/ProjectCrackerTests.fs#L54
